### ISSUE TITLE
DirectionModule crashes without VelocityModule

### ISSUE THREAD

**Issue by anissen** [RudenkoArts/sparkler#4]
DirectionModule crashes if there is no VelocityModule. I have the following setup:

```haxe
modules: [
    new AreaSpawnModule({
        ...
    }),
    new ColorLifeModule({
        ...
    }),
    new SizeLifeModule({
        ...
    }),
    new DirectionModule({
        ...
    })
]
```

Which crashes here: https://github.com/RudenkoArts/sparkler/blob/master/sparkler/modules/DirectionModule.hx#L75

I don't know if it's by-design but it was not required in the "old Sparkler". It does not appear to correct in the README example either (there is a direction module but no velocity module).

**Comment by AndreiRudenko** [comment]
Ye, this happens, just lately find this bug. I will commit with fix, need to test.

**Comment by AndreiRudenko** [comment]
VelocityModule not required, DirectionModule and all that extend VelocityModule will add VelocityUpdateModule with Velocity Component automatically.

**Comment by anissen** [comment]
It works, awesome! Thanks a lot 🎉
